app:
  name: myapp-prod
  replicas: 3
  image:
    repository: nginx
    tag: stable
  service:
    type: LoadBalancer
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi